spring:
  # 数据库配置
  datasource:
    username: yuech
    password: Yue_Chang5
    url: jdbc:mysql://serverhost:3306/carmall?useSSL=false&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    # Hikari数据源配置
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
  # jpa配置
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    # 将默认的存储引擎切换为InnoDB
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  # 热部署配置
  #devtools:
    #restart:
      #poll-interval: 2s
  # thymeleaf配置
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    # 开发时关闭缓存，不热没法看到实时页面
    cache: false
  messages:
    basename: i18n/messages
    encoding: UTF-8
  redis:
    host: serverhost
    port: 6379
    password: yuechang
    database: 5
    jedis:
      pool:
        max-active: 3000
        max-wait: -1
        min-idle: 0
        max-idle: 3000


system:
  temp: temp
  ftpMap:
    hostname: serverhost
    username: kevin
    password: yuechang
    port: 21
    uploadPath: /home/kevin/upload
    suffix: gif,jpeg,jpg,png,bmp
    # maxSize: 1024*1024
    maxSize: 1048576